# Kafka settings
kafka:
  topic:
    read: Tweets
    write: ReTweetStream
  processor: ReTweetFilterProcessor
  consumer:
    group-id: tweet-aggregator
    checker-id: checker
  bootstrap:
    servers: localhost:9092

# Schema registry settings
schema:
  registry:
    url: http://localhost:8081

# Server settings
server:
  port: 10003

# Application settings
info:
  app:
    name: Kafka KStream Consumer Application (Statefull stream processing)
    description: Statefull stream-processing application to read messages from a topic in kafka
    version: 1.0.0

# Actuator settings
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,beans
